name: IaC Pipeline

on:
  push:
    branches:
    - main
    - develop

env:
  TERRAFORM_VERSION  : 1.11.4
  ARM_CLIENT_ID      : ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET  : ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID      : ${{ secrets.ARM_TENANT_ID }}

jobs:

  CI-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: $TERRAFORM_VERSION
    - uses: actions/checkout@v4
    - run : terraform -chdir=./terraform/azure init
    - run : terraform -chdir=./terraform/azure validate

  CD-deploy:
    name: Deploy
    needs: CI-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: $TERRAFORM_VERSION
    - name: Code Checkout
      uses: actions/checkout@v4
    - name: Terraform Init
      run : terraform -chdir=./terraform/azure init
    - name: Terraform Plan
      run : terraform -chdir=./terraform/azure plan -destroy -out tfplan
    - name: Terraform Apply
      run : terraform -chdir=./terraform/azure apply tfplan
    - name: Terraform Show
      run : terraform -chdir=./terraform/azure show